# --- configuration principale -------------------------------------------------
manual_seed: 42  # assure une reproductibilité
dataset:
  name: HDF5Dataset

model:
  name: UNet3D
  in_channels: 1
  out_channels: 1
  initial_feature_maps: 32
  final_sigmoid: true  # régression, pas de sigmoïde en sortie
  layer_order: gcr
  f_maps: [16, 32, 64,128,256]
  num_groups: 8


loss:
  name: BCEDiceLoss  # un bon compromis entre L1 et MSE

eval_metric:
  name: DiceCoefficient     # métrique plus pertinente pour la régression d’image

optimizer:
  learning_rate: 0.0001     # 1e-4 (good starting point for Adam)
  weight_decay: 0.00001     # keep as is

lr_scheduler:
  name: ReduceLROnPlateau
  mode: min                 # we want to minimize validation loss
  factor: 0.5               # reduce LR by half instead of 0.1 (less aggressive)
  patience: 10              # wait 10 epochs before reducing
  cooldown: 2               # wait a bit before resuming LR checks
  min_lr: 0.0000001         # don’t go below 1e-7

trainer:
  eval_score_higher_is_better: True
  checkpoint_dir: "/workspace/capacitynet/data/checkpoint"
  resume: null
  pre_trained: null
  validate_after_iters: 10
  log_after_iters: 10
  max_num_epochs: 500
  max_num_iterations: 15000000

loaders:
  num_workers: 1
  raw_internal_path: raw
  label_internal_path: label

  train:
    file_paths: ["/workspace/capacitynet/data/data_format/train/16_07_2025_01_04_3_group_70.h5"]
    slice_builder:
      name: SliceBuilder
      patch_shape: [152, 152, 152]
      stride_shape: [152, 152, 152]
    transformer:
      raw:
        - name: Identity
        - name: ToTensor
          expand_dims: true
      label:
        - name: Identity
        - name: ToTensor
          expand_dims: true

  val:
    file_paths: ["/workspace/capacitynet/data/data_format/val/16_07_2025_01_04_3_group_70.h5"]
    slice_builder:
      name: SliceBuilder
      patch_shape: [152, 152, 152]
      stride_shape: [152, 152, 152]
    transformer:
      raw:
        - name: Identity
        - name: ToTensor
          expand_dims: true
      label:
        - name: Identity
        - name: ToTensor
          expand_dims: true

train:
  epochs: 200
  batch_size: 1